### ISSUE TITLE
Improve logs viewer

### ISSUE THREAD

**Issue by maciaszczykm** [kubernetes/dashboard#1828]
We should improve logs viewer. There is a list of action items:

- [x] ~Add since time selector (#265)~
- [x] Add option to hide timestamps (#1546 & #1825)
- [x] Aggregate logs across controllers and services
- [x] ~Show logs from time >2 hours~
- [x] Avoid out of memory errors (#1834, possibly #1925 and #1816)
- [x] Support ~tailing and~ following logs (#1083)
- [ ] Buttons in logs view disappear after decreasing window width (#1548)
- [x] How to view logs of crashed pods? #1393

**Comment by cheld** [comment]
https://github.com/kubernetes/dashboard/pull/2007

**Comment by cheld** [comment]
@floreks 

`Add since time selector` does not make much sense any more as we load only part of the log file. We would need better (paging) api support

`Show logs from time >2 hours`

Same for this issue. WDYT?

**Comment by floreks** [comment]
`Show logs from time >2 hours` 

Does not make sense to me also, however `Add since time selector` option should not be that hard even with current implementation and still might be beneficial. In example if user finds that around 2 AM container had very high resource usage then it's nice to have option to easily check logs at this point in time.

`SinceTime` and `LimitBytes` are working together so we should be able to load few pages near provided time frame.

First approach might be limited to just given option to download logs, but in the end such feature might be nice to have.

**Comment by Globegitter** [comment]
It would be nice to be able to increase the height of the log window/the number of lines shown on the screen. Could just be a simple dropdown on the top 50/100/500 lines or something like that.

**Comment by Globegitter** [comment]
Another request that just came up, being able to search through the logs via a search bar - that would be great.

**Comment by maciaszczykm** [comment]
> Another request that just came up, being able to search through the logs via a search bar - that would be great.

Until Kubernetes will provide API for that, we cannot do it on our own. It would kill the whole app. Logs are too big.

**Comment by cheld** [comment]
Once we have implemented the extention framework, we could integrate with ELK

**Comment by Globegitter** [comment]
Just upgraded to 1.7.0 and am not able to download logs, just getting a 404:

```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "the server could not find the requested resource",
  "reason": "NotFound",
  "details": {},
  "code": 404
}
```

**Comment by cheld** [comment]
OK I have a look tomorrow

**Comment by cheld** [comment]
@Globegitter could you please create new issue?

Does the log view show the same error message?

**Comment by Globegitter** [comment]
@cheld done: #2408

**Comment by rars** [comment]
Hi @maciaszczykm. Has a 'since time selector' for logs been added to the dashboard? I can't see it in 2.0.0-beta.4 and wondered if I was missing where it is or if it is planned for a future release? Thanks.

**Comment by maciaszczykm** [comment]
@rars I don't think it was implemented considering the discussion above.
