### ISSUE TITLE
Critical login improvements

### ISSUE THREAD

**Issue by floreks** [kubernetes/dashboard#2207]
List of things to be done before dashboard log in mechanism will be ready for official release. P0 are must have.
Template: [Feature] - [Size] - [Priority]

 - [x] Login status on main toolbar - M - P0 - @maciaszczykm - #2242
   There is option to skip login page. This causes dashboard to use service account privileges mounted into the pod. We also need to give option to log in if user chooses to skip it at first.
- [x] Logout option - M - P0 - @maciaszczykm - #2242
- [x] Rework login page (UX) - M - P2 - @maciaszczykm - #2242  
- [x] Encryption key storing mechanism - XL - P0 - @floreks - #2243
   - [x] Make sure that dashboard with minimal privileges can not see/edit/delete key holder secret - @floreks - #2311
- [x] Token expiration/refresh feature - L - P0 - @floreks - #2316
  [K8S - Certificate manager](https://github.com/kubernetes/kubernetes/tree/master/pkg/kubelet/certificate)
- [x] Restrict login functionality to HTTPS - M - P0 - @maciaszczykm - #2250
- [x] Add more login options: basic, kubeconfig-based - M - P1 - @floreks - #2325
- [x] Add `--authentication-mode` argument that will be responsible for enabling/disabling certain login options in the frontend: M - P1 - @floreks - #2325
- [x] Improve error handling - M - P2 - Done in #2316, #2325
   In case of unexpected error during login status check or token refresh we should logout user and redirect to login page.
- [x] https://github.com/kubernetes/dashboard/issues/2207#issuecomment-321777203
   Fixed by #2316. User will be logged out and redirected to login page if existing token is invalid.

Moved all non-critical features to #2353.

**Comment by maciaszczykm** [comment]
I will implement logout.

**Comment by maciaszczykm** [comment]
There is an issue with login, when I am using one cluster instance and I do have token set in cookies (it means I am logged in) and I switch to another cluster. Token will be still available in cookies, but it won't match any secret and page will crash. We have to check not only if token is available, but if it is valid to avoid this issue.

**Comment by floreks** [comment]
This is on the list. Improved error handling will deal with that. Also cookie is saved for a particular page address so unless 2 daahboards on 2 clusters have same address we are fine.

**Comment by maciaszczykm** [comment]
Yes, I am aware of that, but assuming somebody uses proxy errors could happen.

**Comment by rf232** [comment]
Looking at the proposal in https://github.com/kubernetes/community/pull/887, it might be that to work nicely with RBAC we'll still need a service account with quite some permissions. This (and the JWT encryption key stored in kube-system namespace) would lead me to believe that we don't want the skip authentication button to be available. Or at least be able to be turned off.

**Comment by maciaszczykm** [comment]
I agree with @rf232 here. In such case I would propose adding `--insecure` flag to Dashboard which would skip/turn off whole auth mechanism and use defined service account. However, this would be option for advanced users.

**Comment by floreks** [comment]
Currently we'll only need SA for dashboard with 2 permissions:

This one will allow dashboard to read encryption key. It will be hidden from UI though so only user that is logged and has access to read it will be able to see this secret.
```
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["kubernetes-dashboard-key-holder"]
  verbs: ["get"]
```

Second one will allow dashboard to check apiserver version. This will be the minimal permissions set required to run dashboard after login will be finished.

The reason to have skip button is that some people may want to add some pure read privileges for "anonymous" users that want to skip login page.

**Comment by rf232** [comment]
I guess I missunderstood, since I thought pressing skip would give you Dashboard SA permissions, not anonymous.

**Comment by floreks** [comment]
You understood correctly. It will give you dashboard SA permissions and they will be very limited as I have described above.

**Comment by rf232** [comment]
Is it possible to give it anonymous permissions, so that we don't even leak these permissions?

**Comment by floreks** [comment]
What if anonymous user is disabled in the cluster?

**Comment by rf232** [comment]
Then i'd expect loging in to be required anyway, and not the Dashboard to provide some way around it

**Comment by floreks** [comment]
We can disable `Skip` option but still if you access dashboard over HTTP then login option will be disabled thus allowing people to use default dashboard SA.

**Comment by rf232** [comment]
I'm still thinking what an end-user would expect the dashboard to do. This might be different for different users. I like @maciaszczykm's suggestion about the --insecure version. And perhaps not even listen on HTTP if we run in secure mode and then do require that people log in in this secure mode. I am not sure if that is what all users would expect though

**Comment by bryk** [comment]
Not listening on HTTP sounds like a good idea.

**Comment by floreks** [comment]
I agree with serving either on HTTP or HTTPS only. Currently HTTP is default and only if user provides `--tls-cert-file` and `--tls-key-file` flags HTTPS is enabled. For now I'd only change serving both HTTP and HTTPS at once. At least until we'll add option to auto-generate certificates that can be signed by apiserver CA.
