### ISSUE TITLE
Browser-specific issue tracker

### ISSUE THREAD

**Issue by maciaszczykm** [kubernetes/dashboard#2420]
We are encountering a couple of browser-specific issues as there are many browsers available and we are not able to test the app on all of them. I have created this tracker issue to cleanup issue list a bit.

### Mozilla Firefox

- [x] downloaded log file names are put inside `''` quotes (mentioned in #2439, closed in #2443)

### ~~Internet Explorer~~

- [x] ~~edit resource dialog doesn't get large (mentioned in #945)~~
- [x] ~~full text of the column labels are not shown (mentioned in #948)~~
- [x] ~~some tests were failing and were disabled (mentioned in #794)~~

### Safari

- [x] shell is too short, it has height of 8 (mentioned in #2183)
- [ ] logout button doesn't work, it doesn't remove JWT token cookie (mentioned in #2396)

**Comment by maciaszczykm** [comment]
Closing as most of the issues are resolved in Angular migration, i.e. shell in Safari.

/close
