### ISSUE TITLE
Settings improvements

### ISSUE THREAD

**Issue by maciaszczykm** [kubernetes/dashboard#2618]
- [x] add minimal RBAC create rights of config maps (workaround like in https://github.com/kubernetes/kubernetes/pull/53046)
- [x] disable settings editing if auth was skipped (#2639)
- [ ] enable global settings editing only for specific role/user
- [x] add user-specific settings (also remember sort, filter, namespace etc. after page refresh)
- [x] add language picker where user is able to switch between browser's locale and the one chosen by him (mentioned in #2240)
- [x] add color/theme picker where user is able to pick primary theme's color (mentioned in #1657)

Continuation from https://github.com/kubernetes/dashboard/issues/2417.

**Comment by rahuldhide** [comment]
@maciaszczykm When are we planning to start theme/color picker feature?

**Comment by maciaszczykm** [comment]
@rahuldhide It is a quite low priority for us at the moment.

**Comment by jurgenweber** [comment]
documentation on how to setup and ensure the page works? I get a 403 when accessing the 'settings' page right now and there is nothing in the docs (that I can find), I can see it makes/has made the 'kubernetes-dashboard-settings' configmap.. it has access to it... about it.

**Comment by maciaszczykm** [comment]
@jurgenweber Are you using this role with access privileges to access Dashboard?

**Comment by floreks** [comment]
If you want to be able to access settings page while using `Skip` option then u need to disable settings authorizer.

Check out Dashboard arguments:
https://github.com/kubernetes/dashboard/wiki/Dashboard-arguments

**Comment by sellers** [comment]
The disable-settings-authorizer does not seem to be a valid option in Dashboard 1.8.x?   

unknown flag: --disable-settings-authorizer

**Comment by jurgenweber** [comment]
works fine for me now that I have tried it.

```
      containers:
      - name: kubernetes-dashboard
        image: gcr.io/google_containers/kubernetes-dashboard-amd64:v1.8.2
        ports:
        - containerPort: 8443
          protocol: TCP
        args:
          - --auto-generate-certificates
          - --disable-settings-authorizer
```

**Comment by floreks** [comment]
@sellers It was added in release v1.8.2. https://github.com/kubernetes/dashboard/releases/tag/v1.8.2

**Comment by antoniomo** [comment]
Hi,

This could be a separate issue, but mentioning it here first: If the `kubernetes-dashboard-settings` configmap exists but has no data, the settings dialog fails (assignment to entry in nil map).

**Comment by srfrnk** [comment]
I can confirm what @antoniomo says.
Also as a workaround:
1) Open the dashboard in your browser
1) Set to view the `kube-system` namespace
1) List the `Config Maps` and open `kubernetes-dashboard-settings`
1) Edit
1) Add the following and update:
```json
  "data": {
    "_global": "{\"clusterName\":\"...\",\"itemsPerPage\":50,\"autoRefreshTimeInterval\":1}"
  }
```

The dashboard settings page will allow updates now.

**Comment by sherifkayad** [comment]
@maciaszczykm I see that the task `add color/theme picker where user is able to pick primary theme's color` is already closed .. how can one set this one using the settings? I didn't find any documentation about it.

**Comment by sherifkayad** [comment]
@floreks so there are no plans of adding a custom "primary" color in the settings? That's really nice for cases where one has multiple clusters e.g. PROD / Non-PROD / LAB / .. whatever so that optically the users would get in which one they are if each of these has a custom color ..

**Comment by floreks** [comment]
If there is no issue related to such a feature already open you can create one. I don't remember talking about that. Sounds interesting and should not be hard to achieve.

**Comment by sherifkayad** [comment]
@floreks created #6654 for your reference.
