### ISSUE TITLE
Move wiki documents under @docs/` and update them

### ISSUE THREAD

**Issue by shu-mutou** [kubernetes/dashboard#4008]
##### Reasons

1. Due to instruction by k8s org, only maintainer can edit wiki pages since this year.
2. Therefore, contributor can not propose documentation updates by PR.
3. Wiki contents are out of dates. Partially fairly.
4. Before release 2.0.0, we need to update docs.

##### TODOs

- [x] for `2.0.0 or later`
    - [x] Reorganize `docs/`, create indexes and blank pages. #4009
    - [x] Fill blank pages with new descriptions or add new pages if needed. (divided work)
- [x] for `1.10.1 or before`
    After migration to `docs/`, revert wiki for <=1.10.1.
    - [x] Revert wiki revision to 1.10.1 (to the end of last year). (maintainer only)
    - [x] Add notice for `<=1.10.1` on wiki pages. (maintainer only)
    - [x] Add link to `docs/` for `>=2.0.0`" on wiki pages. (maintainer only)
    - Let's consider migration of docs for `<=1.10.1` later.
    Old documents are all removed.

**Comment by shu-mutou** [comment]
Wiki pages to be migrated and assignee:
- [ ] Common
  - [ ] FAQ
  - [ ] Roadmap
  - [ ] Dashboard arguments
- [ ] User Guide
  - [ ] Installation
  - [ ] Certificate management
  - [ ] Accessing Dashboard
    - [ ] 1.7.X and above
    - [ ] 1.6.X and below
  - [ ] Access control
    - [ ] Creating sample user
  - [ ] Integrations
  - [ ] Labels
- [ ] Development Guide
  - [x] Getting started @shu-mutou 
  - [ ] Release procedures
  - [ ] Dependency management
  - [ ] Architecture
  - [ ] Code conventions
  - [ ] Text conventions
  - [x] Internationalization @shu-mutou

**Comment by maciaszczykm** [comment]
Once the docs are moved we should also update docs button on `About` page in the app.

**Comment by maciaszczykm** [comment]
We should close the Wikis once this will be done.

**Comment by maciaszczykm** [comment]
Arch image should be updated to replace Heapster.

**Comment by maciaszczykm** [comment]
Please also add https://github.com/kubernetes/dashboard/pull/3504#issuecomment-501353220 info to the docs. Can be placed in FAQ or some dev doc.

**Comment by maciaszczykm** [comment]
@jeefy Would be nice if you would describe dev process with the metrics. Some manual, tips etc.

**Comment by shu-mutou** [comment]
> `export GO111MODULE=on` should be part of the docs too.

it would be done in #4169.

**Comment by shu-mutou** [comment]
> `export GO111MODULE=on` should be part of the docs too.

Done in #4169

**Comment by shu-mutou** [comment]
@maciaszczykm @jeefy I'm unlikely to be able to update FAQ, Roadmap and Integrations well. Could you guys update them?

**Comment by maciaszczykm** [comment]
For FAQ, it's worth to mention that `kubectl -n kubernetes-dashboard port-forward svc/dashboard-metrics-scraper 8000:8000` allows to test metrics locally.

**Comment by shu-mutou** [comment]
For FAQ, it's worth to describe increasing kernel setting `fs.inotify.max_user_watches` on host when developer faces `Error: ENOSPC: System limit for number of file watchers reached, watch`.

To increase the parameter, run line `echo fs.inotify.max_user_watches=582222 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p`.

**Comment by nathansmyth** [comment]
These updates are creating broken links support sites, including the issues in this project.

Is there a way to redirect from the wiki to the new address?

For example, going to https://github.com/kubernetes/dashboard/wiki/Creating-sample-user now redirects to the wiki home page. And from what I'm reading in this issue, soon all documentation links will do the same.

Here are two examples of where this issue is occuring:
https://github.com/Azure/aks-engine/issues/805
https://github.com/kubernetes/dashboard/issues/2787

**Comment by maciaszczykm** [comment]
Also https://github.com/kubernetes/dashboard/issues/4121 should be covered by this issue.

**Comment by shu-mutou** [comment]
Wiki contents that should be migrated to `/docs` have fully migrated.
