### ISSUE TITLE
Add plugin support on the frontend

### ISSUE THREAD

**Issue by ajatprabha** [kubernetes/dashboard#4069]
##### What would you like to be added
#4017 adds support for serving plugins from the backend. The dashboard should be able to consume them and mount them in the UI.

##### Why is this needed
See Ref: #1832 

##### TODOs
- [x] Add plugin discovery service to dashboard
- [x] Mount plugins in the UI
- [x] Add routing for plugins
- [x] Error Handling
- [ ] Plugin support feature should be toggleable during production build until a stable version is released

**Comment by ajatprabha** [comment]
Closing since #4094 is merged.
