### ISSUE TITLE
Implement CRD Object Detail Page

### ISSUE THREAD

**Issue by eloyekunle** [kubernetes/dashboard#4123]
##### What would you like to be added
Objects created as CRDs can contain arbitrary JSON/YAML data. It is difficult to display the data in an intuitive way that captures the intended use of the resource. It is proposed that the entire arbitrary JSON/YAML data be shown in a structured text format using the library currently used for the edit dialog.

**Current Object Detail Page**
![image](https://user-images.githubusercontent.com/11166933/61879046-1f2af500-aeea-11e9-8bfa-4b8b8370e2bd.png)

**TODO**
- [x] Implement Object Data view.
- [x] Add Edit & Delete ActionBar buttons.
- [x] Add Events Section.

##### Comments
Credits: [the TPR design proposal](https://github.com/kubernetes/dashboard/blob/db92a80971/docs/design/thirdpartyresources.md).
Ref: #4030 
Ref: #2493

**Comment by eloyekunle** [comment]
Current view of the object detail page:

![image](https://user-images.githubusercontent.com/11166933/62065714-79e48980-b227-11e9-81da-e95450003a49.png)

**Comment by maciaszczykm** [comment]
@eloyekunle Few remarks:

- Ensure that fields from the list are in the details view (is kind there?). You can do it using new tab named `Information` like in other resources.
- I think there is no need to display whole YAML/JSON in spec. I'd display spec only there. We have metadata above. WDYT?

**Comment by eloyekunle** [comment]
The CRD object spec may vary across the CRDs, since each CRD defines the possible fields for the objects. So, I don't think we can come up with a predefined set of fields to display for the object information.
Is my understanding correct?

**Comment by maciaszczykm** [comment]
@eloyekunle Yes, but you can display only part of the YAML.

**Comment by eloyekunle** [comment]
Do you mean e.g. just showing the `spec` and `status` nodes of the YAML?

**Comment by maciaszczykm** [comment]
Yes, exactly. But the whole YAML is also fine in the end.
