### ISSUE TITLE
Implement details pages for resources

### ISSUE THREAD

**Issue by floreks** [kubernetes/dashboard#651]
Here we can track which detail pages should be implemented and what is the current status:

Template: `<Resource name> (<related issue nr>) - <Status> - <Assignee>`
- [x] Namespace (P2) - In progress - @maciaszczykm
- [x] [Pod](https://raw.githubusercontent.com/kubernetes/dashboard/master/docs/design/mockups/23-03-2016-scale-and-navigation/pod-details-page-overview.png) (#650) (P0) - PR: #740 - @digitalfishpond 
- [x] Node (#821) (P1) - Done - @maciaszczykm
- [x] Replica Set (P0) - PR: #730 - @floreks
- [x] [Replication Controller](https://raw.githubusercontent.com/kubernetes/dashboard/master/docs/design/mockups/23-03-2016-scale-and-navigation/rc-details-page-overview.png) (#652) (P0) - PR: #694 - @floreks
- [x] Job (#788) (P0) - Done - @maciaszczykm
- [x] Deployment (P0) - PR: #750 - @Draiken
- [x] Daemon Set (#765) (P0) - Done - @maciaszczykm
- [x] Pet Set (#779) (P2) - Done - @floreks
- [x] [Service](https://raw.githubusercontent.com/kubernetes/dashboard/master/docs/design/mockups/23-03-2016-scale-and-navigation/details-page-template.png) - (#659) (P0) - PR: #726 - @floreks @maciaszczykm
- [x] Ingress (P2) - Done - @bryk
- [x] Persistent Volume Claim - Done - @digitalfishpond
- [x] Persistent Volume - Done - @batikanu 
- [x] Resource Quota - Done - @maciaszczykm
- [x] [Secret](https://raw.githubusercontent.com/kubernetes/dashboard/master/docs/design/mockups/23-03-2016-scale-and-navigation/secret-details-page.png) (P2) - @PiotrDabkowski - Done
- [ ] Limit range - Not started - None
- [ ] Service Account - Not started - None
- [ ] Security Context - Not started - None
- [ ] Image - Not started - None
- [x] ~~Pod template - Not started - None~~
- [x] Config Map - Working - @bryk
- [ ] ScheduledJob - Not started - None

If any resource is missing or not needed then feel free to edit or comment. I've taken this list from our resource research and discussion about app menu.

Should we create separate issue for every resource?
We could also add priorities from our roadmap here. What do you think?

@bryk @cheld @maciaszczykm @digitalfishpond @batikanu

**Comment by bryk** [comment]
> Should we create separate issue for every resource?

I think yes. We'll be having lots of discussions about specific pages, I expect.

**Comment by bryk** [comment]
> We could also add priorities from our roadmap here. What do you think?

I like this  :)

**Comment by bryk** [comment]
@floreks @digitalfishpond Can you please design this in such a way that we can reuse as much as possible for other pages? Can you both sync on this and propose a plan?

**Comment by edouardKaiser** [comment]
Deployment resource can be checked I guess ?
I was wondering, what's the rule regarding releasing beta version before the final candidate ? (how often ? what's the trigger ?).
I would be more than happy to deploy a new version of the dashboard on my cluster with the deployment details, to test it and give some feedbacks if necessary.

**Comment by bryk** [comment]
I'll do beta2 release on Monday. Does this work for you? 

We'd love to have feedback on this, so let's cooperate :)

**Comment by edouardKaiser** [comment]
No problems, that's perfect.

**Comment by bryk** [comment]
Basically, for next four weeks we'll be having weekly betas.

**Comment by bryk** [comment]
I'm on ingress now.

**Comment by therc** [comment]
ScheduledJob?

**Comment by maciaszczykm** [comment]
> ScheduledJob?

@therc Added to the list.

**Comment by rf232** [comment]
duplicate of: #961
